version: "3"
services:
  buckets:
    image: textile/textile:buckets
    restart: always
    volumes:
      - "${REPO_PATH}/buckets:/data/buckets"
    environment:
      - BUCK_LOG_DEBUG
      - BUCK_ADDR_API=0.0.0.0:5000
      - BUCK_ADDR_API_PROXY=0.0.0.0:5050
      - BUCK_ADDR_GATEWAY=0.0.0.0:8000
      - BUCK_DATASTORE_TYPE
      - BUCK_DATASTORE_MONGO_URI
      - BUCK_DATASTORE_MONGO_NAME
      - BUCK_GATEWAY_URL
      - BUCK_GATEWAY_SUBDOMAINS
      - BUCK_GATEWAY_WWW_DOMAIN
      - BUCK_THREADS_ADDR=threads:4000
      - BUCK_IPFS_MULTIADDR=/dns4/ipfs/tcp/5011
      - BUCK_IPNS_REPUBLISH_SCHEDULE
      - BUCK_IPNS_REPUBLISH_CONCURRENCY
      - BUCK_CLOUDFLARE_DNS_ZONE_ID
      - BUCK_CLOUDFLARE_DNS_TOKEN
    ports:
      - "5000:5000"
      - "5050:5050"
      - "8000:8000"
    depends_on:
      - threads
      - ipfs
  threads:
    image: textile/go-threads:534a6d0
    restart: always
    volumes:
      - "${REPO_PATH}/threads:/data/threads"
    environment:
      - THREADS_APIADDR=/ip4/0.0.0.0/tcp/5000
      - THREADS_APIPROXYADDR=/ip4/0.0.0.0/tcp/5050
    ports:
      - "4066:4006"
      - "4066:4006/udp"
      - "4000:5000"
      - "4050:5050"
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    restart: always
    volumes:
      - "${REPO_PATH}/ipfs:/data/ipfs"
    ports:
      - "4011:4001"
      - "4011:4001/udp"
      - "127.0.0.1:5011:5001"
      - "8081:8080"
