version: "3"
services:
  buckets:
    build:
      context: ../../
      dockerfile: ./cmd/buckd/Dockerfile.dev
    volumes:
      - buckets_data:/data/buckets
    platform: linux/amd64
    environment:
      - BUCK_LOG_DEBUG=true
      - BUCK_ADDR_API=0.0.0.0:5000
      - BUCK_ADDR_API_PROXY=0.0.0.0:5050
      - BUCK_ADDR_GATEWAY=0.0.0.0:8000
      - BUCK_DATASTORE_TYPE=badger
      - BUCK_GATEWAY_URL
      - BUCK_GATEWAY_SUBDOMAINS
      - BUCK_GATEWAY_WWW_DOMAIN
      - BUCK_THREADS_ADDR=threads:5000
      - BUCK_THREADS_GATEWAY_URL=http://127.0.0.1:7000
      - BUCK_IPFS_MULTIADDR=/dns4/ipfs/tcp/5001
      - BUCK_IPNS_REPUBLISH_SCHEDULE
      - BUCK_IPNS_REPUBLISH_CONCURRENCY
      - BUCK_CLOUDFLARE_DNS_ZONE_ID
      - BUCK_CLOUDFLARE_DNS_TOKEN
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - threads
      - ipfs
    restart: unless-stopped
  threads:
    image: textile/threads:sha-43a1673
    volumes:
      - threads_data:/data/threads
    platform: linux/amd64
    environment:
      - THREADS_DEBUG=true
      - THREADS_APIADDR=/ip4/0.0.0.0/tcp/5000
      - THREADS_APIPROXYADDR=/ip4/0.0.0.0/tcp/5050
      - THREADS_GATEWAYADDR=0.0.0.0:8000
    ports:
      - "4066:4006"
      - "4066:4006/udp"
      - "127.0.0.1:4050:5050"
      - "127.0.0.1:7000:8000"
    restart: unless-stopped
  ipfs:
    image: textile/go-ipfs:sha-ce693d7
    volumes:
      - ipfs_data:/data/ipfs
    platform: linux/amd64
    environment:
      - IPFS_PROFILE=test
    ports:
      - "4011:4001"
      - "4011:4001/udp"
      - "127.0.0.1:8081:8080"
    restart: unless-stopped
volumes:
  buckets_data:
  threads_data:
  ipfs_data:
