name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: [self-hosted, buckets1]
    container: ubuntu-latest
    services:
      threads:
        image: textile/go-threads:534a6d0
        env:
          THREADS_APIADDR: /ip4/0.0.0.0/tcp/5000
          THREADS_APIPROXYADDR: /ip4/0.0.0.0/tcp/5050
      ipfs:
        image: ipfs/go-ipfs:v0.8.0
        env:
          IPFS_PROFILE: test
    steps:
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v1
      - name: test
        env:
          SKIP_SERVICES: true
          THREADS_API_ADDR: threads:5000
          IPFS_API_MULTIADDR: /dns4/ipfs/tcp/5001
        run: make test
