name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: [self-hosted, buckets1]
    services:
      threads:
        image: textile/go-threads:534a6d0
        env:
          THREADS_APIADDR: /ip4/0.0.0.0/tcp/5000
          THREADS_APIPROXYADDR: /ip4/0.0.0.0/tcp/5050
        ports:
          - 4006:4006
          - 127.0.0.1:4000:5000
          - 127.0.0.1:4050:5050
      ipfs:
        image: ipfs/go-ipfs:v0.8.0
        env:
          IPFS_PROFILE: test
        ports:
          - 127.0.0.1:5001:5001
    steps:
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v1
      - name: test
        env:
          SKIP_SERVICES: true
          THREADS_API_ADDR: threads:4000
          IPFS_API_MULTIADDR: /ip4/127.0.0.1/tcp/5001
        run: go test -v -timeout 30m -race ./...
